language: node_js
nodejs:
- lts/*
cache:
  directories:
  - node_modules
before_install:
- npm install --global gulp-cli typescript
- npm install @types/node github:mihaerzen/mongodb-download
- tsc --project node_modules/mongodb-download
install:
- npm install
- npm run-script build-production
notifications:
  slack:
    rooms:
      secure: "MH9i8nQLXYo72+1+fsHfcGc7UMxG7XpFmH4DKboota8DzlJgBsT7AHUZ/FLoHoX1e/LPCl7ruUJ/r9aRJwyX/X1rRDQQuwosJKhLa3iuqW8UbIUlYLFh85/giBJDw5LxyWxY3DeWdoht4ScALaMNakTSzTUnoIBp3EcbX4vhMCV3RGzqllG/Ky9WYHBD/WTLZOr+OsHcGvqrM5CjwKpaJJHx/7tq93a7I+5/UdEj6xhMN7yjJ4dSA+PfWfE7TdBb9Ga/+I5WWeyG44k63z2h2DWmOa6h/4Iz9NNNsO+suPgKEXD6R70T/LIWKTjntBLFSgqn/hBNB2mZtYu9USdQE+F6Ri4VzLu/EU2oHKCGpLY0wXlmmZFYWalwTR7TgnKbxvgMwqFjF1PaQ4HlMrfw02jO8OHs0uoI/N50qyAxvhWRMzoiRLIWlRP2DEOZFmIrPtgnBjcmqsQHYl58703Rh6ByfZ/8BbYm/fvWi7s86BNmBRHHiVz/K3GtV8PEOSgC8/KHMVwvKQHP5ddpT6rKlmqFK6xgeNi1faSJGPvOg+lKTYYDQQ7AxyFxMNMWEjDN8AMUQQmB8kQjAMYBIEWskHQta0BatcIpjTtKBaOp0grF9DkxfHPo0kHKjzsXSQXpaPLICp+7gvL1jyUVlhrFAa4ty64DPK3rNaF1YwTbauw="
