language: node_js
nodejs:
    - "lts/*"

addons:
    apt:
        packages:
            - mongodb
            
cache:
    directories:
        - "node_modules"

before_install:
    - npm install -g gulp-cli

install:
    - npm install
    - npm run-script build-production
    # maybe we don't need to run build-production? CI runs backend tests only

# script phase calls `npm test` by default

# Note: still need to add:
# SSH + Git deployment to testing.faraway-vision.io
# Slack notifications for builds
